name = "web3-college-workers"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 环境变量配置
[vars]
ENVIRONMENT = "development"

# KV命名空间配置
[[kv_namespaces]]
binding = "COURSE_DATA"
id = "982523e646134467af3366beeea5791a"

[[kv_namespaces]]
binding = "PURCHASE_RECORDS"
id = "0b6554d2d54f4064acedf02bfe9e8a20"

# 开发环境配置
[env.development]
name = "web3-college-workers-dev"

[env.production]
name = "web3-college-workers-prod"
